version: '2'
services:
  e2e-tests:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/edx-e2e-tests
  firefox:
    image: "selenium/standalone-firefox"
    ports:
      - "4444:4444"
    volumes:
      - ./data:/data
